module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Routes', [
      {
        title: 'Route 1',
        map: 'API FROM MAP UNIQUE 1',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 2',
        map: 'API FROM MAP UNIQUE 2',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 3',
        map: 'API FROM MAP UNIQUE 3',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 4',
        map: 'API FROM MAP UNIQUE 4',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 5',
        map: 'API FROM MAP UNIQUE 5',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 6',
        map: 'API FROM MAP UNIQUE 6',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 7',
        map: 'API FROM MAP UNIQUE 7',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 8',
        map: 'API FROM MAP UNIQUE 8',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 9',
        map: 'API FROM MAP UNIQUE 9',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 10',
        map: 'API FROM MAP UNIQUE 10',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 11',
        map: 'API FROM MAP UNIQUE 11',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 12',
        map: 'API FROM MAP UNIQUE 12',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 13',
        map: 'API FROM MAP UNIQUE 13',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 14',
        map: 'API FROM MAP UNIQUE 14',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 15',
        map: 'API FROM MAP UNIQUE 15',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 16',
        map: 'API FROM MAP UNIQUE 16',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 17',
        map: 'API FROM MAP UNIQUE 17',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 18',
        map: 'API FROM MAP UNIQUE 18',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 19',
        map: 'API FROM MAP UNIQUE 19',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 20',
        map: 'API FROM MAP UNIQUE 20',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 21',
        map: 'API FROM MAP UNIQUE 21',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 22',
        map: 'API FROM MAP UNIQUE 22',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'Route 23',
        map: 'API FROM MAP UNIQUE 23',
        user_id: Math.floor(Math.random() * 5 + 1),
        location_id: Math.floor(Math.random() * 5 + 1),
        length_km: Math.floor(Math.random() * 20 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Routes', null, {});
  },
};
