module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Reviews', [
      {
        title: 'text title 1',
        body: 'text body review 1',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 2',
        body: 'text body review 2',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 3',
        body: 'text body review 3',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 4',
        body: 'text body review 4',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 5',
        body: 'text body review 5',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 6',
        body: 'text body review 6',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 7',
        body: 'text body review 7',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 8',
        body: 'text body review 8',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 9',
        body: 'text body review 9',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 10',
        body: 'text body review 10',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 11',
        body: 'text body review 11',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 12',
        body: 'text body review 12',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 13',
        body: 'text body review 13',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 14',
        body: 'text body review 14',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 15',
        body: 'text body review 15',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 16',
        body: 'text body review 16',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 17',
        body: 'text body review 17',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 18',
        body: 'text body review 18',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 19',
        body: 'text body review 19',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 20',
        body: 'text body review 20',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 21',
        body: 'text body review 21',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 22',
        body: 'text body review 22',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 23',
        body: 'text body review 23',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 24',
        body: 'text body review 24',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 25',
        body: 'text body review 25',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 26',
        body: 'text body review 26',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 27',
        body: 'text body review 27',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 28',
        body: 'text body review 28',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 29',
        body: 'text body review 29',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 30',
        body: 'text body review 30',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 31',
        body: 'text body review 31',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 32',
        body: 'text body review 32',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: 'text title 33',
        body: 'text body review 33',
        user_id: Math.floor(Math.random() * 5 + 1),
        route_id: Math.floor(Math.random() * 23 + 1),
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Reviews', null, {});
  },
};
